# Generated by Django 2.2.3 on 2019-07-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190706_1534'),
        ('books', '0004_auto_20190706_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300, verbose_name='评论内容')),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
