# Generated by Django 2.2.3 on 2019-07-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='书籍标题')),
                ('author', models.CharField(max_length=20, verbose_name='书籍作者')),
                ('type_id', models.SmallIntegerField(default=1, verbose_name='书的种类')),
                ('tag', models.CharField(max_length=1024, verbose_name='标签')),
                ('description', models.CharField(max_length=128, verbose_name='简介')),
                ('content_path', models.CharField(max_length=50, verbose_name='书籍保存路径')),
                ('image', models.CharField(max_length=50, verbose_name='封面保存路径')),
                ('view_number', models.IntegerField(verbose_name='浏览量')),
                ('collection_number', models.IntegerField(verbose_name='收藏量')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
