# Generated by Django 2.2.3 on 2019-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190706_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_path',
            field=models.CharField(max_length=200, verbose_name='书籍保存路径'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_path',
            field=models.CharField(default='static/books/pic.jpg', max_length=200, verbose_name='封面保存路径'),
        ),
    ]
