# Generated by Django 2.2.3 on 2019-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190706_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collection_number',
            field=models.IntegerField(default=0, verbose_name='收藏量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_number',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
