# Generated by Django 2.2.2 on 2019-07-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190706_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
    ]
