# Generated by Django 2.2.2 on 2019-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_id',
            field=models.SmallIntegerField(choices=[(1, '仙侠玄幻'), (2, '历史纵横'), (3, '都市言情')], default=1, verbose_name='书的种类'),
        ),
    ]
