# Generated by Django 2.2.3 on 2019-07-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190708_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='download_number',
            field=models.IntegerField(default=0, verbose_name='下载量'),
        ),
    ]
