# Generated by Django 2.2.2 on 2019-07-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_download_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_read',
            field=models.CharField(default='[]', max_length=300, verbose_name='最近浏览'),
        ),
    ]
